version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 12000:12000
        volumes:
            - .env.docker:/var/www/html/.env
        environment:
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
